version: '3.8'
services:
  alarmclockweb:
    container_name: alarmclockweb
    image: alarmclockweb
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./config.php:/var/www/html/config.php:ro
    # If you MQTT broker is running on the host, you should be able to
    # connect to host.docker.internal from within the container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - alarmclockweb

networks:
  alarmclockweb:
    ipam:
      driver: default
    driver_opts:
      com.docker.network.bridge.name: br-acweb
